
export type Zone = {
  name: string;
  avgTemperature: number;
  greenCover: number;
  heatRisk: "High" | "Medium" | "Low";
};

export const cityZones: Record<string, Zone[]> = {
  Bengaluru: [
    { name: "Koramangala", avgTemperature: 29, greenCover: 15, heatRisk: "High" },
    { name: "Indiranagar", avgTemperature: 28.5, greenCover: 18, heatRisk: "High" },
    { name: "Whitefield", avgTemperature: 29.5, greenCover: 20, heatRisk: "High" },
    { name: "Jayanagar", avgTemperature: 26, greenCover: 35, heatRisk: "Medium" },
    { name: "BTM Layout", avgTemperature: 28.8, greenCover: 12, heatRisk: "High" },
    { name: "HSR Layout", avgTemperature: 27.5, greenCover: 25, heatRisk: "Medium" },
    { name: "Electronic City", avgTemperature: 30, greenCover: 10, heatRisk: "High" },
    { name: "Yelahanka", avgTemperature: 26.5, greenCover: 40, heatRisk: "Medium" },
    { name: "Hebbal", avgTemperature: 27, greenCover: 38, heatRisk: "Medium" },
    { name: "Malleshwaram", avgTemperature: 25.5, greenCover: 45, heatRisk: "Low" },
    { name: "Rajajinagar", avgTemperature: 27.8, greenCover: 22, heatRisk: "Medium" },
    { name: "Banashankari", avgTemperature: 26.2, greenCover: 33, heatRisk: "Medium" },
    { name: "Marathahalli", avgTemperature: 29.8, greenCover: 8, heatRisk: "High" },
    { name: "Bellandur", avgTemperature: 29.2, greenCover: 14, heatRisk: "High" },
    { name: "Sarjapur Road", avgTemperature: 28.9, greenCover: 16, heatRisk: "High" },
    { name: "KR Puram", avgTemperature: 29.1, greenCover: 15, heatRisk: "High" },
    { name: "Basavanagudi", avgTemperature: 25, greenCover: 50, heatRisk: "Low" },
    { name: "Vijayanagar", avgTemperature: 27.3, greenCover: 28, heatRisk: "Medium" },
    { name: "Nagarbhavi", avgTemperature: 26.8, greenCover: 32, heatRisk: "Medium" },
    { name: "Kengeri", avgTemperature: 26, greenCover: 42, heatRisk: "Low" },
    { name: "RT Nagar", avgTemperature: 27.2, greenCover: 26, heatRisk: "Medium" },
    { name: "Shivajinagar", avgTemperature: 29.6, greenCover: 5, heatRisk: "High" },
    { name: "Frazer Town", avgTemperature: 27.5, greenCover: 30, heatRisk: "Medium" },
    { name: "Ulsoor", avgTemperature: 26.5, greenCover: 48, heatRisk: "Low" },
    { name: "MG Road", avgTemperature: 29.4, greenCover: 11, heatRisk: "High" },
    { name: "Brigade Road", avgTemperature: 29.7, greenCover: 9, heatRisk: "High" },
    { name: "Domlur", avgTemperature: 28.2, greenCover: 20, heatRisk: "High" },
    { name: "JP Nagar", avgTemperature: 26.7, greenCover: 36, heatRisk: "Medium" },
    { name: "Peenya", avgTemperature: 30.2, greenCover: 7, heatRisk: "High" },
    { name: "Cubbon Park", avgTemperature: 24, greenCover: 80, heatRisk: "Low" },
    { name: "Lalbagh", avgTemperature: 23.8, greenCover: 85, heatRisk: "Low" },
    { name: "Sadashivanagar", avgTemperature: 25.8, greenCover: 55, heatRisk: "Low" },
  ],
  Mumbai: [
    { name: "Colaba", avgTemperature: 30, greenCover: 15, heatRisk: "High" },
    { name: "Dadar", avgTemperature: 31, greenCover: 10, heatRisk: "High" },
    { name: "Andheri", avgTemperature: 30.5, greenCover: 12, heatRisk: "High" },
    { name: "Bandra", avgTemperature: 29.5, greenCover: 20, heatRisk: "Medium" },
    { name: "Juhu", avgTemperature: 29, greenCover: 25, heatRisk: "Medium" },
    { name: "Malad", avgTemperature: 30.8, greenCover: 18, heatRisk: "High" },
    { name: "Borivali", avgTemperature: 28, greenCover: 40, heatRisk: "Low" },
    { name: "Thane", avgTemperature: 31.2, greenCover: 14, heatRisk: "High" },
    { name: "Navi Mumbai", avgTemperature: 30, greenCover: 22, heatRisk: "Medium" },
    { name: "Powai", avgTemperature: 29.8, greenCover: 30, heatRisk: "Medium" },
    { name: "Chembur", avgTemperature: 31.5, greenCover: 8, heatRisk: "High" },
    { name: "Sion", avgTemperature: 31.3, greenCover: 9, heatRisk: "High" },
    { name: "Goregaon", avgTemperature: 29.2, greenCover: 35, heatRisk: "Medium" },
    { name: "Worli", avgTemperature: 30.1, greenCover: 16, heatRisk: "High" },
    { name: "Cuffe Parade", avgTemperature: 30.3, greenCover: 13, heatRisk: "High" },
    { name: "Lower Parel", avgTemperature: 31.8, greenCover: 5, heatRisk: "High" },
    { name: "Kandivali", avgTemperature: 29.9, greenCover: 28, heatRisk: "Medium" },
    { name: "Sanjay Gandhi NP", avgTemperature: 26, greenCover: 85, heatRisk: "Low" },
    { name: "Aarey Colony", avgTemperature: 27.5, greenCover: 60, heatRisk: "Low" },
    { name: "Marine Drive", avgTemperature: 29.7, greenCover: 5, heatRisk: "High" },
    { name: "Bhandup", avgTemperature: 30.4, greenCover: 20, heatRisk: "High" },
    { name: "Vikhroli", avgTemperature: 30.6, greenCover: 25, heatRisk: "Medium" },
    { name: "Ghatkopar", avgTemperature: 31.1, greenCover: 11, heatRisk: "High" },
    { name: "Kurla", avgTemperature: 32, greenCover: 4, heatRisk: "High" },
    { name: "Parel", avgTemperature: 31.6, greenCover: 7, heatRisk: "High" },
    { name: "Mahim", avgTemperature: 30.2, greenCover: 19, heatRisk: "High" },
    { name: "Santacruz", avgTemperature: 30.7, greenCover: 15, heatRisk: "High" },
    { name: "Vile Parle", avgTemperature: 30.4, greenCover: 22, heatRisk: "Medium" },
    { name: "Mira Road", avgTemperature: 31.4, greenCover: 17, heatRisk: "High" },
    { name: "Bhayandar", avgTemperature: 31.7, greenCover: 13, heatRisk: "High" },
    { name: "Churchgate", avgTemperature: 30.5, greenCover: 10, heatRisk: "High" },
    { name: "Fort", avgTemperature: 30.9, greenCover: 12, heatRisk: "High" },
  ],
  "New Delhi": [
    { name: "Connaught Place", avgTemperature: 33, greenCover: 15, heatRisk: "High" },
    { name: "Chandni Chowk", avgTemperature: 34, greenCover: 5, heatRisk: "High" },
    { name: "Karol Bagh", avgTemperature: 33.5, greenCover: 10, heatRisk: "High" },
    { name: "Lutyens' Delhi", avgTemperature: 29, greenCover: 60, heatRisk: "Low" },
    { name: "Hauz Khas", avgTemperature: 30, greenCover: 40, heatRisk: "Medium" },
    { name: "Greater Kailash", avgTemperature: 31, greenCover: 30, heatRisk: "Medium" },
    { name: "Dwarka", avgTemperature: 32.5, greenCover: 20, heatRisk: "High" },
    { name: "Rohini", avgTemperature: 32.8, greenCover: 25, heatRisk: "High" },
    { name: "Nehru Place", avgTemperature: 33.8, greenCover: 8, heatRisk: "High" },
    { name: "Lajpat Nagar", avgTemperature: 33.2, greenCover: 12, heatRisk: "High" },
    { name: "Saket", avgTemperature: 31.5, greenCover: 35, heatRisk: "Medium" },
    { name: "Vasant Kunj", avgTemperature: 30.8, greenCover: 45, heatRisk: "Medium" },
    { name: "Chanakyapuri", avgTemperature: 29.5, greenCover: 70, heatRisk: "Low" },
    { name: "Paharganj", avgTemperature: 34.2, greenCover: 3, heatRisk: "High" },
    { name: "Mayur Vihar", avgTemperature: 31.8, greenCover: 28, heatRisk: "Medium" },
    { name: "Pitampura", avgTemperature: 32.6, greenCover: 22, heatRisk: "High" },
    { name: "Rajouri Garden", avgTemperature: 32.9, greenCover: 18, heatRisk: "High" },
    { name: "Tilak Nagar", avgTemperature: 33.6, greenCover: 14, heatRisk: "High" },
    { name: "Okhla", avgTemperature: 33.9, greenCover: 10, heatRisk: "High" },
    { name: "Siri Fort", avgTemperature: 29.8, greenCover: 55, heatRisk: "Low" },
    { name: "Mehrauli", avgTemperature: 32, greenCover: 38, heatRisk: "Medium" },
    { name: "Jahanpanah City Forest", avgTemperature: 28.5, greenCover: 75, heatRisk: "Low" },
    { name: "South Extension", avgTemperature: 32.2, greenCover: 25, heatRisk: "High" },
    { name: "Khan Market", avgTemperature: 31.4, greenCover: 33, heatRisk: "Medium" },
    { name: "Anand Vihar", avgTemperature: 34.1, greenCover: 7, heatRisk: "High" },
    { name: "Lodi Garden", avgTemperature: 29.2, greenCover: 80, heatRisk: "Low" },
    { name: "Moti Bagh", avgTemperature: 30.5, greenCover: 50, heatRisk: "Low" },
    { name: "Defence Colony", avgTemperature: 31.2, greenCover: 38, heatRisk: "Medium" },
    { name: "Kamla Nagar", avgTemperature: 33.3, greenCover: 13, heatRisk: "High" },
    { name: "Noida Sector 18", avgTemperature: 33.7, greenCover: 11, heatRisk: "High" },
    { name: "Gurgaon Cyber City", avgTemperature: 34.5, greenCover: 6, heatRisk: "High" },
    { name: "Old Delhi", avgTemperature: 34.3, greenCover: 4, heatRisk: "High" },
  ],
  Chennai: [
    { name: "T. Nagar", avgTemperature: 32.5, greenCover: 10, heatRisk: "High" },
    { name: "Adyar", avgTemperature: 30, greenCover: 40, heatRisk: "Medium" },
    { name: "Anna Nagar", avgTemperature: 31, greenCover: 30, heatRisk: "Medium" },
    { name: "Mylapore", avgTemperature: 31.5, greenCover: 20, heatRisk: "High" },
    { name: "Velachery", avgTemperature: 32, greenCover: 15, heatRisk: "High" },
    { name: "Guindy", avgTemperature: 29.5, greenCover: 55, heatRisk: "Low" },
    { name: "Besant Nagar", avgTemperature: 30.5, greenCover: 35, heatRisk: "Medium" },
    { name: "OMR", avgTemperature: 32.8, greenCover: 12, heatRisk: "High" },
    { name: "Nungambakkam", avgTemperature: 31.8, greenCover: 25, heatRisk: "High" },
    { name: "Royapettah", avgTemperature: 32.2, greenCover: 18, heatRisk: "High" },
    { name: "Parrys Corner", avgTemperature: 33, greenCover: 5, heatRisk: "High" },
    { name: "Egmore", avgTemperature: 31.9, greenCover: 22, heatRisk: "High" },
    { name: "Kodambakkam", avgTemperature: 32.1, greenCover: 17, heatRisk: "High" },
    { name: "Tambaram", avgTemperature: 32.4, greenCover: 14, heatRisk: "High" },
    { name: "Ashok Nagar", avgTemperature: 31.2, greenCover: 28, heatRisk: "Medium" },
    { name: "Vadapalani", avgTemperature: 32.6, greenCover: 11, heatRisk: "High" },
    { name: "Perambur", avgTemperature: 32.9, greenCover: 9, heatRisk: "High" },
    { name: "IIT Madras Campus", avgTemperature: 29, greenCover: 70, heatRisk: "Low" },
    { name: "Koyambedu", avgTemperature: 33.2, greenCover: 8, heatRisk: "High" },
    { name: "Marina Beach", avgTemperature: 31, greenCover: 5, heatRisk: "High" },
    { name: "Saidapet", avgTemperature: 31.7, greenCover: 20, heatRisk: "High" },
    { name: "Chromepet", avgTemperature: 32.3, greenCover: 16, heatRisk: "High" },
    { name: "Alandur", avgTemperature: 32, greenCover: 19, heatRisk: "High" },
    { name: "Porur", avgTemperature: 32.7, greenCover: 13, heatRisk: "High" },
    { name: "Madipakkam", avgTemperature: 31.6, greenCover: 24, heatRisk: "Medium" },
    { name: "Nanganallur", avgTemperature: 31.4, greenCover: 26, heatRisk: "Medium" },
    { name: "Theosophical Society", avgTemperature: 29.2, greenCover: 80, heatRisk: "Low" },
    { name: "ECR", avgTemperature: 30.8, greenCover: 33, heatRisk: "Medium" },
    { name: "Ambattur", avgTemperature: 33.1, greenCover: 10, heatRisk: "High" },
    { name: "Avadi", avgTemperature: 33.3, greenCover: 12, heatRisk: "High" },
    { name: "George Town", avgTemperature: 33.5, greenCover: 4, heatRisk: "High" },
    { name: "Triplicane", avgTemperature: 32.5, greenCover: 7, heatRisk: "High" },
  ],
  Hyderabad: [
    { name: "Hitech City", avgTemperature: 31.5, greenCover: 15, heatRisk: "High" },
    { name: "Gachibowli", avgTemperature: 31, greenCover: 20, heatRisk: "High" },
    { name: "Banjara Hills", avgTemperature: 29, greenCover: 40, heatRisk: "Medium" },
    { name: "Jubilee Hills", avgTemperature: 28.5, greenCover: 45, heatRisk: "Low" },
    { name: "Secunderabad", avgTemperature: 30.5, greenCover: 25, heatRisk: "Medium" },
    { name: "Kukatpally", avgTemperature: 32, greenCover: 12, heatRisk: "High" },
    { name: "Ameerpet", avgTemperature: 32.5, greenCover: 8, heatRisk: "High" },
    { name: "Begumpet", avgTemperature: 31.2, greenCover: 18, heatRisk: "High" },
    { name: "Madhapur", avgTemperature: 31.8, greenCover: 14, heatRisk: "High" },
    { name: "Koti", avgTemperature: 33, greenCover: 5, heatRisk: "High" },
    { name: "Charminar", avgTemperature: 32.8, greenCover: 7, heatRisk: "High" },
    { name: "Dilsukhnagar", avgTemperature: 32.6, greenCover: 10, heatRisk: "High" },
    { name: "Uppal", avgTemperature: 31.9, greenCover: 16, heatRisk: "High" },
    { name: "LB Nagar", avgTemperature: 32.2, greenCover: 13, heatRisk: "High" },
    { name: "Mehdipatnam", avgTemperature: 32.4, greenCover: 11, heatRisk: "High" },
    { name: "Osmania University", avgTemperature: 29.5, greenCover: 50, heatRisk: "Low" },
    { name: "KBR National Park", avgTemperature: 27.5, greenCover: 85, heatRisk: "Low" },
    { name: "Necklace Road", avgTemperature: 30, greenCover: 30, heatRisk: "Medium" },
    { name: "Abids", avgTemperature: 32.9, greenCover: 6, heatRisk: "High" },
    { name: "Himayatnagar", avgTemperature: 31.7, greenCover: 22, heatRisk: "Medium" },
    { name: "Nampally", avgTemperature: 32.7, greenCover: 9, heatRisk: "High" },
    { name: "Somajiguda", avgTemperature: 31.4, greenCover: 24, heatRisk: "Medium" },
    { name: "Tarnaka", avgTemperature: 31.6, greenCover: 21, heatRisk: "High" },
    { name: "Miyapur", avgTemperature: 31.8, greenCover: 17, heatRisk: "High" },
    { name: "Kondapur", avgTemperature: 31.3, greenCover: 19, heatRisk: "High" },
    { name: "Manikonda", avgTemperature: 30.8, greenCover: 26, heatRisk: "Medium" },
    { name: "Alwal", avgTemperature: 30.2, greenCover: 33, heatRisk: "Medium" },
    { name: "Sainikpuri", avgTemperature: 29.8, greenCover: 42, heatRisk: "Medium" },
    { name: "ECIL Cross Roads", avgTemperature: 32.1, greenCover: 15, heatRisk: "High" },
    { name: "Falaknuma", avgTemperature: 32.3, greenCover: 12, heatRisk: "High" },
    { name: "Golconda Fort", avgTemperature: 30.4, greenCover: 35, heatRisk: "Medium" },
    { name: "Hyderabad Botanical Garden", avgTemperature: 28, greenCover: 75, heatRisk: "Low" },
  ],
  Kolkata: [
    { name: "Park Street", avgTemperature: 31.5, greenCover: 15, heatRisk: "High" },
    { name: "Salt Lake", avgTemperature: 31, greenCover: 30, heatRisk: "Medium" },
    { name: "New Town", avgTemperature: 30.5, greenCover: 35, heatRisk: "Medium" },
    { name: "Howrah", avgTemperature: 32.5, greenCover: 8, heatRisk: "High" },
    { name: "Ballygunge", avgTemperature: 30, greenCover: 40, heatRisk: "Medium" },
    { name: "Dum Dum", avgTemperature: 32, greenCover: 20, heatRisk: "High" },
    { name: "Esplanade", avgTemperature: 33, greenCover: 5, heatRisk: "High" },
    { name: "Alipore", avgTemperature: 29.5, greenCover: 55, heatRisk: "Low" },
    { name: "Jadavpur", avgTemperature: 31.2, greenCover: 25, heatRisk: "Medium" },
    { name: "Behala", avgTemperature: 31.8, greenCover: 18, heatRisk: "High" },
    { name: "Shyambazar", avgTemperature: 32.8, greenCover: 10, heatRisk: "High" },
    { name: "Tollygunge", avgTemperature: 30.8, greenCover: 33, heatRisk: "Medium" },
    { name: "Maidan", avgTemperature: 29, greenCover: 70, heatRisk: "Low" },
    { name: "Gariahat", avgTemperature: 32.2, greenCover: 12, heatRisk: "High" },
    { name: "Sealdah", avgTemperature: 33.2, greenCover: 4, heatRisk: "High" },
    { name: "Rajarhat", avgTemperature: 31.4, greenCover: 28, heatRisk: "Medium" },
    { name: "Bidhannagar", avgTemperature: 31.1, greenCover: 32, heatRisk: "Medium" },
    { name: "College Street", avgTemperature: 32.9, greenCover: 7, heatRisk: "High" },
    { name: "Eco Park", avgTemperature: 29.8, greenCover: 65, heatRisk: "Low" },
    { name: "Rabindra Sarobar", avgTemperature: 29.2, greenCover: 68, heatRisk: "Low" },
    { name: "Kalighat", avgTemperature: 32.4, greenCover: 14, heatRisk: "High" },
    { name: "Entally", avgTemperature: 32.6, greenCover: 11, heatRisk: "High" },
    { name: "Barasat", avgTemperature: 32.1, greenCover: 19, heatRisk: "High" },
    { name: "Baguiati", avgTemperature: 31.9, greenCover: 21, heatRisk: "High" },
    { name: "Kankurgachi", avgTemperature: 31.6, greenCover: 24, heatRisk: "Medium" },
    { name: "Ultadanga", avgTemperature: 31.7, greenCover: 22, heatRisk: "High" },
    { name: "New Alipore", avgTemperature: 30.2, greenCover: 45, heatRisk: "Low" },
    { name: "Santoshpur", avgTemperature: 31.3, greenCover: 26, heatRisk: "Medium" },
    { name: "Lake Gardens", avgTemperature: 30.4, greenCover: 48, heatRisk: "Low" },
    { name: "Central Avenue", avgTemperature: 33.1, greenCover: 6, heatRisk: "High" },
    { name: "Dalhousie Square", avgTemperature: 33.3, greenCover: 9, heatRisk: "High" },
    { name: "Botanical Gardens", avgTemperature: 28.5, greenCover: 85, heatRisk: "Low" },
  ],
  Pune: [
    { name: "Koregaon Park", avgTemperature: 28.5, greenCover: 40, heatRisk: "Medium" },
    { name: "Deccan Gymkhana", avgTemperature: 29, greenCover: 35, heatRisk: "Medium" },
    { name: "Hinjewadi", avgTemperature: 30.5, greenCover: 15, heatRisk: "High" },
    { name: "Viman Nagar", avgTemperature: 30, greenCover: 20, heatRisk: "High" },
    { name: "Kothrud", avgTemperature: 28, greenCover: 45, heatRisk: "Low" },
    { name: "Wakad", avgTemperature: 30.2, greenCover: 18, heatRisk: "High" },
    { name: "Aundh", avgTemperature: 28.8, greenCover: 38, heatRisk: "Medium" },
    { name: "Pimpri-Chinchwad", avgTemperature: 31, greenCover: 12, heatRisk: "High" },
    { name: "Hadapsar", avgTemperature: 30.8, greenCover: 14, heatRisk: "High" },
    { name: "Baner", avgTemperature: 29.5, greenCover: 25, heatRisk: "Medium" },
    { name: "Kharadi", avgTemperature: 30.6, greenCover: 16, heatRisk: "High" },
    { name: "Shivaji Nagar", avgTemperature: 29.8, greenCover: 22, heatRisk: "High" },
    { name: "Magarpatta", avgTemperature: 29.2, greenCover: 30, heatRisk: "Medium" },
    { name: "Camp", avgTemperature: 30.1, greenCover: 19, heatRisk: "High" },
    { name: "Swargate", avgTemperature: 31.2, greenCover: 8, heatRisk: "High" },
    { name: "Pune University", avgTemperature: 27.5, greenCover: 60, heatRisk: "Low" },
    { name: "Talawade IT Park", avgTemperature: 31.5, greenCover: 10, heatRisk: "High" },
    { name: "Pashan", avgTemperature: 28.2, greenCover: 50, heatRisk: "Low" },
    { name: "Bhosari", avgTemperature: 31.4, greenCover: 9, heatRisk: "High" },
    { name: "Katraj", avgTemperature: 29.4, greenCover: 28, heatRisk: "Medium" },
    { name: "Warje", avgTemperature: 29.1, greenCover: 33, heatRisk: "Medium" },
    { name: "Bibvewadi", avgTemperature: 29.9, greenCover: 24, heatRisk: "Medium" },
    { name: "Yerwada", avgTemperature: 30.4, greenCover: 17, heatRisk: "High" },
    { name: "Kalyani Nagar", avgTemperature: 29.6, greenCover: 26, heatRisk: "Medium" },
    { name: "Vishrantwadi", avgTemperature: 29.7, greenCover: 23, heatRisk: "High" },
    { name: "Nigdi", avgTemperature: 30.9, greenCover: 13, heatRisk: "High" },
    { name: "Model Colony", avgTemperature: 28.6, greenCover: 42, heatRisk: "Medium" },
    { name: "Laxmi Road", avgTemperature: 31.1, greenCover: 6, heatRisk: "High" },
    { name: "FC Road", avgTemperature: 29.3, greenCover: 29, heatRisk: "Medium" },
    { name: "JM Road", avgTemperature: 29.5, greenCover: 27, heatRisk: "Medium" },
    { name: "Sinhagad Road", avgTemperature: 28.9, greenCover: 36, heatRisk: "Medium" },
    { name: "Empress Garden", avgTemperature: 27, greenCover: 75, heatRisk: "Low" },
  ],
  Mangaluru: [
    { name: "Hampankatta", avgTemperature: 30, greenCover: 10, heatRisk: "High" },
    { name: "Lalbagh", avgTemperature: 29, greenCover: 25, heatRisk: "Medium" },
    { name: "Kadri", avgTemperature: 28.5, greenCover: 40, heatRisk: "Low" },
    { name: "Bejai", avgTemperature: 29.5, greenCover: 20, heatRisk: "Medium" },
    { name: "Surathkal", avgTemperature: 30.5, greenCover: 15, heatRisk: "High" },
    { name: "Ullal", avgTemperature: 29.2, greenCover: 30, heatRisk: "Medium" },
    { name: "Derebail", avgTemperature: 28.8, greenCover: 35, heatRisk: "Medium" },
    { name: "Pumpwell", avgTemperature: 30.2, greenCover: 12, heatRisk: "High" },
    { name: "Kankanady", avgTemperature: 30.1, greenCover: 14, heatRisk: "High" },
    { name: "Pilikula", avgTemperature: 27, greenCover: 70, heatRisk: "Low" },
    { name: "Panambur", avgTemperature: 30.8, greenCover: 8, heatRisk: "High" },
    { name: "Bunder", avgTemperature: 31, greenCover: 5, heatRisk: "High" },
    { name: "Attavar", avgTemperature: 29.8, greenCover: 18, heatRisk: "High" },
    { name: "Falnir", avgTemperature: 29.6, greenCover: 22, heatRisk: "Medium" },
    { name: "Urwa", avgTemperature: 29.4, greenCover: 28, heatRisk: "Medium" },
    { name: "Kavoor", avgTemperature: 29.7, greenCover: 24, heatRisk: "Medium" },
    { name: "Yeyyadi", avgTemperature: 29.3, greenCover: 32, heatRisk: "Medium" },
    { name: "Kulshekar", avgTemperature: 29.1, greenCover: 34, heatRisk: "Medium" },
    { name: "Bondel", avgTemperature: 28.9, greenCover: 38, heatRisk: "Medium" },
    { name: "Mangaladevi", avgTemperature: 30.4, greenCover: 16, heatRisk: "High" },
    { name: "Kottara Chowki", avgTemperature: 30.6, greenCover: 13, heatRisk: "High" },
    { name: "Tannirbhavi", avgTemperature: 29.9, greenCover: 45, heatRisk: "Low" },
    { name: "Sasihithlu", avgTemperature: 29, greenCover: 50, heatRisk: "Low" },
    { name: "Jeppu", avgTemperature: 30.3, greenCover: 17, heatRisk: "High" },
    { name: "Car Street", avgTemperature: 30.7, greenCover: 9, heatRisk: "High" },
    { name: "Bikarnakatte", avgTemperature: 29.5, greenCover: 29, heatRisk: "Medium" },
    { name: "Nanthoor", avgTemperature: 30, greenCover: 19, heatRisk: "High" },
    { name: "St. Aloysius College", avgTemperature: 28.7, greenCover: 42, heatRisk: "Low" },
    { name: "Padil", avgTemperature: 29.8, greenCover: 26, heatRisk: "Medium" },
    { name: "Baikampady", avgTemperature: 31.2, greenCover: 7, heatRisk: "High" },
    { name: "Ashok Nagar", avgTemperature: 29.6, greenCover: 23, heatRisk: "Medium" },
    { name: "NITK Campus", avgTemperature: 28.4, greenCover: 55, heatRisk: "Low" },
  ],
  Mysuru: [
    { name: "Devaraja Market", avgTemperature: 28, greenCover: 5, heatRisk: "High" },
    { name: "Saraswathipuram", avgTemperature: 25.5, greenCover: 40, heatRisk: "Low" },
    { name: "Jayalakshmipuram", avgTemperature: 25.8, greenCover: 38, heatRisk: "Medium" },
    { name: "Kuvempunagar", avgTemperature: 26, greenCover: 35, heatRisk: "Medium" },
    { name: "Hebbal Industrial Area", avgTemperature: 29, greenCover: 10, heatRisk: "High" },
    { name: "Vijayanagar", avgTemperature: 26.5, greenCover: 30, heatRisk: "Medium" },
    { name: "Chamundi Hill", avgTemperature: 24, greenCover: 70, heatRisk: "Low" },
    { name: "Mysore Palace", avgTemperature: 27, greenCover: 20, heatRisk: "Medium" },
    { name: "Infosys Campus", avgTemperature: 25, greenCover: 50, heatRisk: "Low" },
    { name: "KRS Road", avgTemperature: 26.8, greenCover: 25, heatRisk: "Medium" },
    { name: "Ramakrishnanagar", avgTemperature: 26.2, greenCover: 33, heatRisk: "Medium" },
    { name: "Siddhartha Layout", avgTemperature: 27.2, greenCover: 22, heatRisk: "Medium" },
    { name: "Gokulam", avgTemperature: 25.7, greenCover: 42, heatRisk: "Low" },
    { name: "Nazarbad", avgTemperature: 27.5, greenCover: 18, heatRisk: "High" },
    { name: "Lashkar Mohalla", avgTemperature: 27.8, greenCover: 15, heatRisk: "High" },
    { name: "Vontikoppal", avgTemperature: 26.1, greenCover: 36, heatRisk: "Medium" },
    { name: "Yadavagiri", avgTemperature: 25.9, greenCover: 39, heatRisk: "Low" },
    { name: "Brindavan Gardens", avgTemperature: 24.5, greenCover: 80, heatRisk: "Low" },
    { name: "Metagalli", avgTemperature: 28.5, greenCover: 12, heatRisk: "High" },
    { name: "Kukkarahalli Lake", avgTemperature: 25.2, greenCover: 65, heatRisk: "Low" },
    { name: "Ashokapuram", avgTemperature: 27.6, greenCover: 17, heatRisk: "High" },
    { name: "Chamrajpet", avgTemperature: 27.9, greenCover: 14, heatRisk: "High" },
    { name: "NR Mohalla", avgTemperature: 27.4, greenCover: 20, heatRisk: "Medium" },
    { name: "TK Layout", avgTemperature: 26.4, greenCover: 31, heatRisk: "Medium" },
    { name: "JP Nagar", avgTemperature: 26.6, greenCover: 29, heatRisk: "Medium" },
    { name: "Bannimantap", avgTemperature: 28.2, greenCover: 11, heatRisk: "High" },
    { name: "Rajiv Nagar", avgTemperature: 26.9, greenCover: 26, heatRisk: "Medium" },
    { name: "Alanahalli", avgTemperature: 26.7, greenCover: 28, heatRisk: "Medium" },
    { name: "Dattagalli", avgTemperature: 26.3, greenCover: 32, heatRisk: "Medium" },
    { name: "University Campus", avgTemperature: 25.4, greenCover: 55, heatRisk: "Low" },
    { name: "Lalithadripura", avgTemperature: 25.6, greenCover: 48, heatRisk: "Low" },
    { name: "Ittegagud", avgTemperature: 27.7, greenCover: 16, heatRisk: "High" },
  ],
  Coimbatore: [
    { name: "Gandhipuram", avgTemperature: 31, greenCover: 8, heatRisk: "High" },
    { name: "RS Puram", avgTemperature: 29, greenCover: 35, heatRisk: "Medium" },
    { name: "Saibaba Colony", avgTemperature: 29.5, greenCover: 30, heatRisk: "Medium" },
    { name: "Peelamedu", avgTemperature: 30.5, greenCover: 15, heatRisk: "High" },
    { name: "Singanallur", avgTemperature: 30.8, greenCover: 12, heatRisk: "High" },
    { name: "Race Course", avgTemperature: 28, greenCover: 60, heatRisk: "Low" },
    { name: "Town Hall", avgTemperature: 31.5, greenCover: 5, heatRisk: "High" },
    { name: "Ukkadam", avgTemperature: 31.2, greenCover: 10, heatRisk: "High" },
    { name: "Saravanampatti", avgTemperature: 30.2, greenCover: 18, heatRisk: "High" },
    { name: "Vadavalli", avgTemperature: 28.8, greenCover: 40, heatRisk: "Medium" },
    { name: "Edayarpalayam", avgTemperature: 29.8, greenCover: 25, heatRisk: "Medium" },
    { name: "Ramanathapuram", avgTemperature: 30.6, greenCover: 14, heatRisk: "High" },
    { name: "Ganapathy", avgTemperature: 30.9, greenCover: 11, heatRisk: "High" },
    { name: "Hope College", avgTemperature: 30.7, greenCover: 13, heatRisk: "High" },
    { name: "Tidel Park", avgTemperature: 31.1, greenCover: 9, heatRisk: "High" },
    { name: "Ondipudur", avgTemperature: 30.4, greenCover: 16, heatRisk: "High" },
    { name: "Podanur", avgTemperature: 30, greenCover: 20, heatRisk: "High" },
    { name: "Kavundampalayam", avgTemperature: 29.9, greenCover: 22, heatRisk: "Medium" },
    { name: "Thudiyalur", avgTemperature: 29.6, greenCover: 28, heatRisk: "Medium" },
    { name: "Cheran-ma-nagar", avgTemperature: 29.7, greenCover: 26, heatRisk: "Medium" },
    { name: "VOC Park", avgTemperature: 28.5, greenCover: 55, heatRisk: "Low" },
    { name: "Botanical Garden (TNAU)", avgTemperature: 27.5, greenCover: 75, heatRisk: "Low" },
    { name: "Ukkadam Lake", avgTemperature: 29.2, greenCover: 33, heatRisk: "Medium" },
    { name: "Valankulam Lake", avgTemperature: 29.3, greenCover: 32, heatRisk: "Medium" },
    { name: "Perur", avgTemperature: 28.9, greenCover: 38, heatRisk: "Medium" },
    { name: "Kuniyamuthur", avgTemperature: 29.4, greenCover: 31, heatRisk: "Medium" },
    { name: "Sitra", avgTemperature: 30.3, greenCover: 17, heatRisk: "High" },
    { name: "Neelambur", avgTemperature: 30.1, greenCover: 19, heatRisk: "High" },
    { name: "Ettimadai", avgTemperature: 28.6, greenCover: 45, heatRisk: "Low" },
    { name: "Madukkarai", avgTemperature: 29, greenCover: 36, heatRisk: "Medium" },
    { name: "Gandhimanagar", avgTemperature: 30, greenCover: 21, heatRisk: "High" },
    { name: "Sowripalayam", avgTemperature: 29.8, greenCover: 24, heatRisk: "Medium" },
  ],
  Thane: [
    { name: "Thane West", avgTemperature: 31.2, greenCover: 14, heatRisk: "High" },
    { name: "Thane East", avgTemperature: 31.5, greenCover: 12, heatRisk: "High" },
    { name: "Ghodbunder Road", avgTemperature: 30.8, greenCover: 25, heatRisk: "Medium" },
    { name: "Majiwada", avgTemperature: 31.8, greenCover: 10, heatRisk: "High" },
    { name: "Vasant Vihar", avgTemperature: 30.5, greenCover: 30, heatRisk: "Medium" },
    { name: "Kolshet", avgTemperature: 31, greenCover: 20, heatRisk: "High" },
    { name: "Manpada", avgTemperature: 30.9, greenCover: 28, heatRisk: "Medium" },
    { name: "Naupada", avgTemperature: 31.6, greenCover: 15, heatRisk: "High" },
    { name: "Pokhran Road", avgTemperature: 30.2, greenCover: 35, heatRisk: "Medium" },
    { name: "Upvan Lake Area", avgTemperature: 29.5, greenCover: 50, heatRisk: "Low" },
    { name: "Wagle Estate", avgTemperature: 32, greenCover: 5, heatRisk: "High" },
    { name: "Kalwa", avgTemperature: 31.7, greenCover: 13, heatRisk: "High" },
    { name: "Mumbra", avgTemperature: 32.2, greenCover: 8, heatRisk: "High" },
    { name: "Diva", avgTemperature: 32.5, greenCover: 10, heatRisk: "High" },
    { name: "Patlipada", avgTemperature: 30.7, greenCover: 26, heatRisk: "Medium" },
    { name: "Hiranandani Estate", avgTemperature: 30.4, greenCover: 32, heatRisk: "Medium" },
    { name: "Balkum", avgTemperature: 31.3, greenCover: 18, heatRisk: "High" },
    { name: "Ovale", avgTemperature: 31.1, greenCover: 22, heatRisk: "High" },
    { name: "Anand Nagar", avgTemperature: 31.4, greenCover: 16, heatRisk: "High" },
    { name: "Kasarvadavali", avgTemperature: 30.6, greenCover: 29, heatRisk: "Medium" },
    { name: "Lokmanya Nagar", avgTemperature: 31.9, greenCover: 11, heatRisk: "High" },
    { name: "Savarkar Nagar", avgTemperature: 31.8, greenCover: 14, heatRisk: "High" },
    { name: "Dombivli", avgTemperature: 32.1, greenCover: 9, heatRisk: "High" },
    { name: "Kalyan", avgTemperature: 32.4, greenCover: 7, heatRisk: "High" },
    { name: "Ulhasnagar", avgTemperature: 32.6, greenCover: 6, heatRisk: "High" },
    { name: "Ambernath", avgTemperature: 32.3, greenCover: 12, heatRisk: "High" },
    { name: "Badlapur", avgTemperature: 31.5, greenCover: 20, heatRisk: "High" },
    { name: "Talao Pali", avgTemperature: 30, greenCover: 40, heatRisk: "Medium" },
    { name: "Yeoor Hills", avgTemperature: 28, greenCover: 70, heatRisk: "Low" },
    { name: "Shilphata", avgTemperature: 32.8, greenCover: 5, heatRisk: "High" },
    { name: "Vrindavan Society", avgTemperature: 30.3, greenCover: 33, heatRisk: "Medium" },
    { name: "Khopat", avgTemperature: 31.7, greenCover: 12, heatRisk: "High" }
  ],
  // Add other cities here...
  "Nagpur": [
    { name: "Sitabuldi", avgTemperature: 33, greenCover: 10, heatRisk: "High" },
    { name: "Dharampeth", avgTemperature: 31, greenCover: 30, heatRisk: "Medium" },
    { name: "Ramdaspeth", avgTemperature: 31.5, greenCover: 25, heatRisk: "Medium" },
    { name: "Civil Lines", avgTemperature: 30, greenCover: 50, heatRisk: "Low" },
    { name: "MIHAN", avgTemperature: 34, greenCover: 5, heatRisk: "High" },
    { name: "Butibori", avgTemperature: 34.5, greenCover: 8, heatRisk: "High" },
    { name: "Sadar", avgTemperature: 32, greenCover: 20, heatRisk: "High" },
    { name: "Mahal", avgTemperature: 33.5, greenCover: 12, heatRisk: "High" },
    { name: "Nandanvan", avgTemperature: 32.8, greenCover: 15, heatRisk: "High" },
    { name: "Pratap Nagar", avgTemperature: 31.8, greenCover: 28, heatRisk: "Medium" },
    { name: "Manish Nagar", avgTemperature: 32.5, greenCover: 18, heatRisk: "High" },
    { name: "Trimurti Nagar", avgTemperature: 31.9, greenCover: 26, heatRisk: "Medium" },
    { name: "Wardhaman Nagar", avgTemperature: 33.2, greenCover: 14, heatRisk: "High" },
    { name: "Itwari", avgTemperature: 33.8, greenCover: 7, heatRisk: "High" },
    { name: "Jaripatka", avgTemperature: 33.4, greenCover: 11, heatRisk: "High" },
    { name: "Koradi", avgTemperature: 34.2, greenCover: 9, heatRisk: "High" },
    { name: "Kamptee", avgTemperature: 34.1, greenCover: 10, heatRisk: "High" },
    { name: "Hingna", avgTemperature: 33.9, greenCover: 13, heatRisk: "High" },
    { name: "Futala Lake", avgTemperature: 30.5, greenCover: 40, heatRisk: "Medium" },
    { name: "Ambazari Lake", avgTemperature: 30.2, greenCover: 45, heatRisk: "Low" },
    { name: "Seminary Hills", avgTemperature: 29.5, greenCover: 60, heatRisk: "Low" },
    { name: "Gorewada", avgTemperature: 29, greenCover: 70, heatRisk: "Low" },
    { name: "Shankar Nagar", avgTemperature: 31.2, greenCover: 32, heatRisk: "Medium" },
    { name: "Laxmi Nagar", avgTemperature: 31.6, greenCover: 29, heatRisk: "Medium" },
    { name: "Besant Road", avgTemperature: 32.1, greenCover: 22, heatRisk: "High" },
    { name: "Dhantoli", avgTemperature: 31.4, greenCover: 35, heatRisk: "Medium" },
    { name: "Gandhibagh", avgTemperature: 33.6, greenCover: 8, heatRisk: "High" },
    { name: "Mominpura", avgTemperature: 33.7, greenCover: 6, heatRisk: "High" },
    { name: "Pardi", avgTemperature: 34, greenCover: 10, heatRisk: "High" },
    { name: "Wathoda", avgTemperature: 33.3, greenCover: 16, heatRisk: "High" },
    { name: "Sonegaon", avgTemperature: 32.3, greenCover: 24, heatRisk: "Medium" },
    { name: "Viveka Hospital Area", avgTemperature: 31.7, greenCover: 27, heatRisk: "Medium" }
  ],
  "Kochi": [
    { name: "MG Road", avgTemperature: 31.5, greenCover: 10, heatRisk: "High" },
    { name: "Fort Kochi", avgTemperature: 30, greenCover: 40, heatRisk: "Medium" },
    { name: "Edapally", avgTemperature: 31.8, greenCover: 15, heatRisk: "High" },
    { name: "Kakkanad", avgTemperature: 31.2, greenCover: 25, heatRisk: "Medium" },
    { name: "Marine Drive", avgTemperature: 31.6, greenCover: 5, heatRisk: "High" },
    { name: "Panampilly Nagar", avgTemperature: 30.5, greenCover: 35, heatRisk: "Medium" },
    { name: "Vyttila", avgTemperature: 32, greenCover: 12, heatRisk: "High" },
    { name: "Kaloor", avgTemperature: 31.9, greenCover: 14, heatRisk: "High" },
    { name: "Aluva", avgTemperature: 31.4, greenCover: 20, heatRisk: "High" },
    { name: "Mattancherry", avgTemperature: 31, greenCover: 18, heatRisk: "High" },
    { name: "Palarivattom", avgTemperature: 31.7, greenCover: 16, heatRisk: "High" },
    { name: "Thripunithura", avgTemperature: 30.8, greenCover: 30, heatRisk: "Medium" },
    { name: "Willingdon Island", avgTemperature: 31.1, greenCover: 22, heatRisk: "Medium" },
    { name: "Thevara", avgTemperature: 30.9, greenCover: 28, heatRisk: "Medium" },
    { name: "Kadavanthra", avgTemperature: 31.3, greenCover: 24, heatRisk: "Medium" },
    { name: "Elamakkara", avgTemperature: 30.7, greenCover: 32, heatRisk: "Medium" },
    { name: "Subhash Park", avgTemperature: 30.2, greenCover: 50, heatRisk: "Low" },
    { name: "Mangalavanam Bird Sanctuary", avgTemperature: 29.5, greenCover: 70, heatRisk: "Low" },
    { name: "Infopark", avgTemperature: 32.2, greenCover: 10, heatRisk: "High" },
    { name: "SmartCity", avgTemperature: 32.1, greenCover: 12, heatRisk: "High" },
    { name: "Cherai Beach", avgTemperature: 30.4, greenCover: 25, heatRisk: "Medium" },
    { name: "Maradu", avgTemperature: 31.5, greenCover: 18, heatRisk: "High" },
    { name: "Goshree Islands", avgTemperature: 30.6, greenCover: 38, heatRisk: "Medium" },
    { name: "Bolgatty Island", avgTemperature: 30.1, greenCover: 45, heatRisk: "Low" },
    { name: "Kundannoor", avgTemperature: 31.8, greenCover: 13, heatRisk: "High" },
    { name: "Kalamassery", avgTemperature: 31.6, greenCover: 19, heatRisk: "High" },
    { name: "Angamaly", avgTemperature: 31.2, greenCover: 26, heatRisk: "Medium" },
    { name: "Perumbavoor", avgTemperature: 31.3, greenCover: 23, heatRisk: "Medium" },
    { name: "Thrikkakara", avgTemperature: 31, greenCover: 27, heatRisk: "Medium" },
    { name: "Chottanikkara", avgTemperature: 30.8, greenCover: 33, heatRisk: "Medium" },
    { name: "Ernakulam Town", avgTemperature: 32.1, greenCover: 8, heatRisk: "High" },
    { name: "Jawaharlal Nehru Stadium", avgTemperature: 32.3, greenCover: 7, heatRisk: "High" }
  ],
  "Kasaragod": [
    { "name": "Kasaragod Town", "avgTemperature": 31.5, "greenCover": 15, "heatRisk": "High" },
    { "name": "Kanhangad", "avgTemperature": 31.2, "greenCover": 25, "heatRisk": "Medium" },
    { "name": "Nileshwaram", "avgTemperature": 30.8, "greenCover": 35, "heatRisk": "Medium" },
    { "name": "Uppala", "avgTemperature": 32, "greenCover": 12, "heatRisk": "High" },
    { "name": "Manjeshwar", "avgTemperature": 31.7, "greenCover": 20, "heatRisk": "High" },
    { "name": "Bekal Fort", "avgTemperature": 30.5, "greenCover": 45, "heatRisk": "Low" },
    { "name": "Cherkala", "avgTemperature": 31.8, "greenCover": 18, "heatRisk": "High" },
    { "name": "Vidyanagar", "avgTemperature": 31.6, "greenCover": 22, "heatRisk": "High" },
    { "name": "Chandragiri", "avgTemperature": 30.9, "greenCover": 30, "heatRisk": "Medium" },
    { "name": "Trikaripur", "avgTemperature": 31, "greenCover": 28, "heatRisk": "Medium" },
    { "name": "Anandashram", "avgTemperature": 30, "greenCover": 50, "heatRisk": "Low" },
    { "name": "Kottachery", "avgTemperature": 31.3, "greenCover": 24, "heatRisk": "Medium" },
    { "name": "Pallikere Beach", "avgTemperature": 30.7, "greenCover": 40, "heatRisk": "Low" },
    { "name": "Padne", "avgTemperature": 31.1, "greenCover": 26, "heatRisk": "Medium" },
    { "name": "Kumbla", "avgTemperature": 31.9, "greenCover": 16, "heatRisk": "High" },
    { "name": "Madhur", "avgTemperature": 31, "greenCover": 33, "heatRisk": "Medium" },
    { "name": "Cheruvathur", "avgTemperature": 30.6, "greenCover": 38, "heatRisk": "Low" },
    { "name": "Udma", "avgTemperature": 31.4, "greenCover": 23, "heatRisk": "High" },
    { "name": "Periye", "avgTemperature": 30.4, "greenCover": 42, "heatRisk": "Low" },
    { "name": "Bandadka", "avgTemperature": 30.2, "greenCover": 48, "heatRisk": "Low" },
    { "name": "Hosdurg", "avgTemperature": 31.2, "greenCover": 27, "heatRisk": "Medium" },
    { "name": "Mogral Puthur", "avgTemperature": 32.1, "greenCover": 14, "heatRisk": "High" },
    { "name": "Badiyadka", "avgTemperature": 30.8, "greenCover": 34, "heatRisk": "Medium" },
    { "name": "Ranipuram", "avgTemperature": 28, "greenCover": 75, "heatRisk": "Low" },
    { "name": "Talapady", "avgTemperature": 32.2, "greenCover": 13, "heatRisk": "High" },
    { "name": "Paivalike", "avgTemperature": 31, "greenCover": 31, "heatRisk": "Medium" },
    { "name": "Vellarikundu", "avgTemperature": 29.5, "greenCover": 60, "heatRisk": "Low" },
    { "name": "Delampady", "avgTemperature": 29.8, "greenCover": 55, "heatRisk": "Low" },
    { "name": "Kasaragod Port", "avgTemperature": 32.3, "greenCover": 10, "heatRisk": "High" },
    { "name": "Mangalpady", "avgTemperature": 31.8, "greenCover": 19, "heatRisk": "High" },
    { "name": "Meenja", "avgTemperature": 31.5, "greenCover": 21, "heatRisk": "High" }
  ]
};
